server:
  port: 8080
services:
  auth-service:
    id: AUTH-SERVER
    v1:
      api: /api/v1/auth
      name: AUTH-SERVER_V1
spring:
  application:
    name: MY_ROOM-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
            
        - id: BOOKING-SERVICE
          uri: http://booking-service.bef24bd.kyma.ondemand.com
          predicates:
            - Path=/api/v1/booking-service/**
          filters:
            - AuthenticationFilter
            
        - id: ROOM-SERVICE
          uri: http://room-service.bef24bd.kyma.ondemand.com
          predicates:
            - Path=/api/v1/room-service/**
          filters:
            - AuthenticationFilter
            
        - id: ORGANIZATION-SERVICE
          uri: http://organization-service.bef24bd.kyma.ondemand.com
          predicates:
            - Path=/api/v1/organization-service/**
          filters:
            - AuthenticationFilter
            
        - id: ONBOARDING-SERVICE
          uri: http://onboarding-service.bef24bd.kyma.ondemand.com
          predicates:
            - Path=/api/v1/onboarding/**
          filters:
            - AuthenticationFilter

        - id: ORGANIZATION-PAY-SERVICE
          uri: http://54.196.65.193:8087
          predicates:
            - Path=/api/v1/organizationpay/**
          filters:
            - AuthenticationFilter
            
        - id: PAYMENT-SERVICE
          uri: http://payment-service.bef24bd.kyma.ondemand.com
          predicates:
            - Path=/api/v1/payment-service/**
          filters:
            - AuthenticationFilter
            
        - id: REVIEW-SERVICE
          uri: http://review-service.bef24bd.kyma.ondemand.com
          predicates:
            - Path=/api/v1/review-service/**
          filters:
            - AuthenticationFilter
# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://3.229.47.37:8761/eureka
